# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qrvc < Formula
  desc "Use the command line to make a QR code from a vCard"
  homepage "https://github.com/ulfschneider/qrvc"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ulfschneider/qrvc/releases/download/v0.11.0/qrvc_Darwin_x86_64.tar.gz"
      sha256 "73be96cf98142b820db5e3a980fd5488be8a86176d4fcd4d5c08c4836b08d855"

      def install
        bin.install "qrvc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ulfschneider/qrvc/releases/download/v0.11.0/qrvc_Darwin_arm64.tar.gz"
      sha256 "bc150b387a19d58d2e5dae035ce36bc27d3bec889afc7f32ddeff8dcaf7705f5"

      def install
        bin.install "qrvc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ulfschneider/qrvc/releases/download/v0.11.0/qrvc_Linux_x86_64.tar.gz"
      sha256 "732bed0dd8085ba18659b8841f05995ebe8bbb28e41906bb70ea8f4f8d01a2cf"
      def install
        bin.install "qrvc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ulfschneider/qrvc/releases/download/v0.11.0/qrvc_Linux_arm64.tar.gz"
      sha256 "3d1ca8ed9119d3cb506e665480e0151e965158513a29ea7abec58fe33f54179c"
      def install
        bin.install "qrvc"
      end
    end
  end

  test do
    system "#{bin}/qrvc", "--version"
  end
end
