# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qrvc < Formula
  desc "Use the command line to make a QR code from a vCard"
  homepage "https://github.com/ulfschneider/qrvc"
  version "0.10.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ulfschneider/qrvc/releases/download/v0.10.8/qrvc_Darwin_x86_64.tar.gz"
      sha256 "2bafdd762443841909cce9846307be59d95453330a8bced672136d03f530d6ce"

      def install
        bin.install "qrvc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ulfschneider/qrvc/releases/download/v0.10.8/qrvc_Darwin_arm64.tar.gz"
      sha256 "256687baa084b741e0e10a72cbbf549f6214da994e73e3f2fd9df660920c1ec2"

      def install
        bin.install "qrvc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ulfschneider/qrvc/releases/download/v0.10.8/qrvc_Linux_x86_64.tar.gz"
      sha256 "5b4e9c781b5350a8f6a656029b9085e9914578514415efbaf2d8feb4bfe10ef3"
      def install
        bin.install "qrvc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ulfschneider/qrvc/releases/download/v0.10.8/qrvc_Linux_arm64.tar.gz"
      sha256 "aaf8e442219fd9657ea5436d8df874d144c6ca113281f1069a96c83436447981"
      def install
        bin.install "qrvc"
      end
    end
  end

  test do
    system "#{bin}/qrvc", "--version"
  end
end
