# This file was generated by GoReleaser. DO NOT EDIT.
cask "qrvc" do
  name "qrvc"
  desc "Use the command line to make a QR code from a vCard"
  homepage "https://github.com/ulfschneider/qrvc"
  version "0.11.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qrvc"

  on_macos do
    on_intel do
      url "https://github.com/ulfschneider/qrvc/releases/download/v#{version}/qrvc_Darwin_amd64.tar.gz",
        verified: "github.com/ulfschneider/qrvc"
      sha256 "f6a391bb819dd72d863d858def8faf4d331ee820ecf4b0672b3de733419f681a"
    end
    on_arm do
      url "https://github.com/ulfschneider/qrvc/releases/download/v#{version}/qrvc_Darwin_arm64.tar.gz",
        verified: "github.com/ulfschneider/qrvc"
      sha256 "5092b1f69a449ac793a69e65332d0309a2fa23415d552a61f54b84c97f76973f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ulfschneider/qrvc/releases/download/v#{version}/qrvc_Linux_amd64.tar.gz",
        verified: "github.com/ulfschneider/qrvc"
      sha256 "96f435dab755c1ff3c948074260f5eecd5ee71fa3a5145f5ded65471d375e852"
    end
    on_arm do
      url "https://github.com/ulfschneider/qrvc/releases/download/v#{version}/qrvc_Linux_arm64.tar.gz",
        verified: "github.com/ulfschneider/qrvc"
      sha256 "5ccd87b8a8ad47339e2dcf33f332f77e6fbb76502bedcbba2d6ff65824e870b5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/qrvc"]
    end
  end

  # No zap stanza required
end
