# This file was generated by GoReleaser. DO NOT EDIT.
cask "qrvc" do
  name "qrvc"
  desc "Use the command line to make a QR code from a vCard"
  homepage "https://github.com/ulfschneider/qrvc"
  version "0.11.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qrvc"

  on_macos do
    on_intel do
      url "https://github.com/ulfschneider/qrvc/releases/download/v#{version}/qrvc_Darwin_amd64.tar.gz",
        verified: "github.com/ulfschneider/qrvc"
      sha256 "72d4f9dc84534972699d80df547256b4b072885e2269862e54378038aefdf80d"
    end
    on_arm do
      url "https://github.com/ulfschneider/qrvc/releases/download/v#{version}/qrvc_Darwin_arm64.tar.gz",
        verified: "github.com/ulfschneider/qrvc"
      sha256 "60bee87d3d5fdb7f3bbfcd3541e3d0bfe1b3a2cd8aa7a4b2435ae78da15639d0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ulfschneider/qrvc/releases/download/v#{version}/qrvc_Linux_amd64.tar.gz",
        verified: "github.com/ulfschneider/qrvc"
      sha256 "90634a884a81eb290a3dc4f7fcb0df5075ef7706035cb0893a48998352610ce8"
    end
    on_arm do
      url "https://github.com/ulfschneider/qrvc/releases/download/v#{version}/qrvc_Linux_arm64.tar.gz",
        verified: "github.com/ulfschneider/qrvc"
      sha256 "37b67298d1bbfc2308563aafdb186f9e48488d9d10e7aac8dd7553c26ca679d0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/qrvc"]
    end
  end

  # No zap stanza required
end
